---
title: "The Lake Game 2024"
output: 
  html_document:
    includes:
      in_header: header.html
    theme: yeti
    css: "bootstrap.css"
    #collapsed: no
    #fig_caption: yes
    #number_sections: no
    #smooth_scroll: yes
    #toc: no
    #toc_float: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(pacman)
p_load(here, ggplot2, ggspatial, sf, dplyr, tidyr, chroma, rnaturalearthdata, gsheet, plotly, DT)


```


```{r data download and cleaning}
url <- construct_download_url("https://docs.google.com/spreadsheets/d/1tcSxnIrAz6tnGWijpZ35WQaOtFICSiVnFsOnugcX_wo/edit", format="csv")
data <- gsheet2tbl(url)[-1,] # download and remove the example row
data$points <- rowSums(data[,5:10])
```


# Leaderboards {.tabset}

## Overall

```{r leaderboard}
summ <- data %>% group_by(name) %>% summarize(Total = sum(points)) %>% arrange(desc(Total)) %>% rename(Name=name)

DT::datatable(summ, rownames=FALSE)

```

## Nudists

```{r nudists}
summ2 <- data %>% group_by(name) %>% summarize(Nudity_Points = sum(nude_1)) %>% arrange(desc(Nudity_Points)) %>% rename(Name=name)

DT::datatable(summ2, rownames=FALSE)

```

## Drinkers

```{r drinkers}
summ3 <- data %>% group_by(name) %>% summarize(Shotguns = sum(beer_1)) %>% arrange(desc(Shotguns)) %>% rename(Name=name)

DT::datatable(summ3, rownames=FALSE)

```

## Hikers

```{r hikers}
summ4 <- data %>% group_by(name) %>% summarize(Hikes = sum(hike_1)) %>% arrange(desc(Hikes)) %>% rename(Name=name)

DT::datatable(summ4, rownames=FALSE)

```

## Cold

```{r cold}
summ5 <- data %>% group_by(name) %>% summarize(Cold_Points = sum(cold_points_0.5)) %>% arrange(desc(Cold_Points)) %>% rename(Name=name)

DT::datatable(summ5, rownames=FALSE)

```


# Map

```{r map, warning=FALSE}

# get map layers
map <- rnaturalearth::ne_states(c("united states of america", "canada"), returnclass = 'sf')
world <- rnaturalearth::ne_countries(returnclass='sf')
world <- sf::st_transform(world, crs=4326)
can <- sf::st_transform(map, crs=4326)


basemap <- world %>% filter(admin != "Canada", admin != "United States of America")  %>% 
  ggplot() + 
  geom_sf(color="grey50", fill="white", linewidth=0.3) +
  geom_sf(data=can, color="grey50", fill="white", linewidth=0.3) + 
  geom_spatial_point(data=data, aes(x=long, y=lat, group=waterbody, size=points, text=paste("player:", name)), 
                     crs=4326, colour="navy", alpha=0.5) +
  coord_sf(xlim=c(-160, -110), ylim=c(48, 70), default_crs = sf::st_crs(4326)) +
  labs(x="Longitude (°E)", y="Latitude (°N)") +
  scale_size(range=c(1.5,3)) +
  theme_bw() + 
  theme( panel.grid = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank(),
         axis.title = element_blank(),
         panel.border = element_rect(colour = "grey60", fill=NA, size=3),
         panel.background = element_rect(fill='transparent'), 
         plot.background = element_rect(fill='transparent'))

ggplotly(basemap, tooltip=c("group", "text", "size")) %>% 
  config(modeBarButtonsToRemove = c("lasso2d", "select2d", "autoscale2d", "hoverClosestCartesian", "hoverCompareCartesian"), scrollZoom = TRUE) %>% layout(dragmode='pan')

```

```{r OLD data cleaning, eval=FALSE}

# read data 
data <- read.csv(here('The_Lake_Game-no_limits.csv'), na.strings="")
data <- data[-1,]


data <- data %>% select(c("c", "Emily.Yungwirth", "Emily.Yungwirth.xy", "Mermaid.man", "Mermaid.man.xy")) %>% rename(lake=c, coords.emily=Emily.Yungwirth.xy, coords.evan=Mermaid.man.xy)

# pivot it
data2 <- data %>% pivot_longer(cols=c("coords.emily", "coords.evan"), values_to="coords") %>% select(!c("name"))

# regex insanity!!!
data2$coords <- gsub("\\(", "", data2$coords)
data2$coords <- gsub("\\)", "", data2$coords)
data2$lat <- gsub("\\,.*", "", data2$coords)
data2$lon <- gsub(".*\\,", "", data2$coords)
data2$lat <- as.numeric(gsub(" ", "", data2$lat))
data2$lon <- as.numeric(gsub(" ", "", data2$lon))

# remove rows with all NAs 
data3 <- data2 %>% filter(!is.na(coords)) %>% select(!c("coords")) %>% mutate(name=if_else(is.na(Mermaid.man), "Emily", "Evan")) %>% mutate(points = if_else(!is.na(Mermaid.man), Mermaid.man, Emily.Yungwirth))

data4 <- data3 %>% mutate(sternum=1, 
                 dunk=if_else(points>=2, 1, 0), 
                 nude=if_else(points>=3, 1, 0),
                 beer=if_else(points>=4, 1, 0),
                 hike=if_else(points>=5, 1, 0)) %>%
  select(!c("Emily.Yungwirth", "Mermaid.man"))

 

```

# Lake Game Rules


